/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Libreria;

/**
 *
 * @author Pedro
 */
public class agregarLibroDigital extends javax.swing.JPanel {

    /**
     * Creates new form agregarLibroDigital
     */
    public agregarLibroDigital() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAgregarLibroDigital = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1200, 700));

        pnlAgregarLibroDigital.setBackground(new java.awt.Color(153, 255, 204));
        pnlAgregarLibroDigital.setPreferredSize(new java.awt.Dimension(1200, 700));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAgregarLibroDigitalLayout = new javax.swing.GroupLayout(pnlAgregarLibroDigital);
        pnlAgregarLibroDigital.setLayout(pnlAgregarLibroDigitalLayout);
        pnlAgregarLibroDigitalLayout.setHorizontalGroup(
            pnlAgregarLibroDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgregarLibroDigitalLayout.createSequentialGroup()
                .addContainerGap(1119, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addContainerGap())
        );
        pnlAgregarLibroDigitalLayout.setVerticalGroup(
            pnlAgregarLibroDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarLibroDigitalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresar)
                .addContainerGap(672, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAgregarLibroDigital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAgregarLibroDigital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
                Menú menu = new Menú();
                menu.pnlMenu.setBounds(this.getBounds());
                this.removeAll();
                this.add(menu.pnlMenu);
                this.updateUI();
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel pnlAgregarLibroDigital;
    // End of variables declaration//GEN-END:variables
}
